name: Eleventy Build

on:
  workflow_dispatch:  # Allows manual trigger for testing
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version compatible with your project

      # Step 3: Install dependencies and build the site
      - name: Install and Build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          allow_empty_commit: true  # Optional: if there's no change, allow an empty commit
          force_orphan: true       # Optional: force push if the branch doesn't exist